name: Tech Challenge - Order Manager - CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --output out/

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: out/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: out/

      - name: Test Module Core/Application
        run: dotnet test ./Tests/Core/ApplicationTests/

      - name: SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
